- name: Trabajar con archivos
  hosts: 10.2.1.136

  vars:
    fichero: /tmp/prueba.txt

  tasks:
    - name: Crear un fichero vacío
      ansible.builtin.copy:
        dest: "{{fichero}}"
        owner: phytsvh
        group: wheel
        content: |
          Esto es un texto de prueba
          Esta es otra línea de prueba
        mode: 644
        
    - name: Cambiar permisos de un fichero
      ansible.builtin.file:
        path: "{{fichero}}"
        owner: phytsvh
        group: root
        mode: 777
      become: True